version: '3.9'

volumes:
    app_data:
        name: app_data

services:
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./:/app

    postgres:
        image: postgres:15.1-alpine3.17
        volumes:
            - app_data:/var/lib/postgresql/data
        ports:
            - ${DJANGO_POSTGRES_PORT:-5432}:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres